[tool.black]
line-length = 99
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']

[tool.isort]  # black config
profile = "black"
line_length = 99

[tool.ruff]
line-length = 99
target-version = "py37"
select = ["E", "F", "I", "PL", "UP", "RUF"]

[tool.ruff.pylint]
max-args = 100
max-statements = 100
max-branches = 40
max-returns = 15
